INSERT INTO category (id, title, created_at, updated_at, deleted_at) VALUES
('1', 'Romance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('2', 'Terror', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('3', 'Mistério', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('4', 'Fantasia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('5', 'Histórico', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('6', 'Aventura', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('7', 'Policial', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('8', 'Poesia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);